name: ume_kit_monitor
description: use ume_kit_monitor to check more net log

version: 0.0.1
homepage: https://github.com/fastcode555/Json2Dart_Null_Safety.git

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_ume: '>=0.3.0'
  flutter:
    sdk: flutter
  device_info_plus:
  cached_network_image:
  dio:
  teledart:
  oktoast:
  path_provider:
  crypto:
  convert:
  url_launcher: