name: ume_kit_monitor
description: use ume_kit_monitor to check more net log

version: 1.0.0
homepage: https://github.com/fastcode555/ume_kit_monitor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_ume: '>=0.3.0'
  flutter:
    sdk: flutter
  cached_network_image:
  dio:
  teledart:
  oktoast:
  path_provider:
  crypto:
  convert:
  url_launcher: