name: ume_kit_monitor
description: use ume_kit_monitor to show more infomation contain log,page,curl,response,json

version: 1.1.0
homepage: https://github.com/fastcode555/ume_kit_monitor

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter_ume: '>=0.3.0'
  flutter:
    sdk: flutter
  dio:
  oktoast:
  path_provider:
  crypto:
  convert:
  url_launcher:
  json_shrink_widget: